### ISSUE TITLE
Correct way of doing that

### ISSUE THREAD

**Issue by VladShcherbin** [meteorhacks/flow-router#36] opened 2015-03-17 08:52 UTC
Okay, I would like to switch iron router, but I have to make sure I understand everything correct and ask some questions.

Lets take a shop example with admin part.
The basic admin layout is:
```
sidebar | main-contents
```
All admin parts must check for a logged in user and his permissions. I should probably use middleware for the check.

**_1**. How can I check all admin routes with this middleware function ? I can specify this in each route, but if there are 100 routes, this is not so cool. I can do a global middleware, but I want this only for admin part, not the whole website. What is the solution?

**_2**. In the sidebar there is orders counter, so it is shared across all the admin routes. As far as I understand, route subscriptions are re-run on route check. I want the global orders subscription for all admin routes. Global subscription is again for the whole website. I can use template helpers, but.. the router aims to do that kind of stuff, yes? What is the solution?

Next part is the orders page. I want to use flow layout. The layout is like the admin one, but with an upgrade.
```
sidebar | orders-list | selected order
```
**_3**. Can I nest the admin layout, insert in the `main-contents` part the template with 2 dynamic parts and then insert this two parts. Smth like:
```
FlowLayout.render('admin-layout', { 
    sidebar: "admin-sidebar", main-contents: "admin-two-sections",
    // This is the admin-two-sections 2 dynamic parts
    left-section: "admin-orders-list", right-part: "admin-selected-order"
});
```
Or should I create a new admin-orders layout and duplicate sidebar there ?

**_4**. As we can see, I use the same sidebar everywhere and have to specify this in every route. With default Meteor behaviour I can make an admin-layout and insert the sidebar template there. `{{> admin-sidebar}}`. Is this the preferred way to do with the flow layout?

**_5**. The three routes: 
`/admin/orders`, `/admin/orders/:id`, `/admin/orders/:id/edit` use the sidebar and orders-list, so that the only `selected order` part is changed. Again, I have to copy-paste this in every route. The orders-list shares the global admin subscription and should not re-run on route changes. What is the solution ?

**_6**. I want named routes, for example `/admin/orders` named as `admin.orders.index` and `/admin/orders/:id` as `admin.orders.show`. Plus, I want a template helper to insert the path for me.
`<a href="helperName 'admin.orders.show' id">{{title}}</a>`. This is not included, am I right?

So, all in all, what is the way to nest routes, templates and share subscriptions? Some kind of *controllers* or **route groups** stuff, where I can nest the layout, subscriptions, middleware stuff and only add the needed ones?

**Comment by arunoda** [comment] 2015-03-17 09:33
A huge list. I'm not sure I answered all. We don't have some features and we removed it by design. May be others can build such API as separate packages.

1) Not sure how you handle routes. If you've 100 routes. Seems like there's something wrong. Anyway, you can check that with a global middleware. It's first argument is path. You can do something with that.

2) We've global subscriptions too. Check docs

3) You can do it with nested dynamic templates, but better to create a new layout

4) Oh yes. Flow layout simply manage Meteor layout. It tries to avoid re-rendering as possible as it can.

5) Not sure. But you can create a function and re-use it. Can't tell much without looking at a code.

6) We don't have named routes. We try to not to provide template helpers. We think it's an anti pattern. Check [FlowRouter.path](https://github.com/meteorhacks/flow-router#flowrouterpathpathdef-params-queryparams)

Bonas Question) We don't have built in way to do this kind of stuff. You can do layout nesting by using dynamic templates inside a template. We are using [Flow Components](https://github.com/meteorhacks/flow-components) along with these. That makes us to build complex layouts.

**Comment by VladShcherbin** [comment] 2015-03-17 10:23
@arunoda oh, you are blazing fast. that is super cool

1) Of course, I don't have 100 routes, just a random number, ha. Okay, lets take some routes:
/admin
/admin/orders
/admin/orders/:id
/admin/orders/:id/slug
/admin/products
/admin/products/:id
..etc

how can I add middleware filter to check if the user is logged in and has permission.
Do I have to specify middleware in every route?
Global are global, I don't want this middleware filter on non-admin pages.

*I am a Laravel guy, love their router and will tell you how it is done there - maybe we can or already have smth similar ?*

```
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', function()
    {
        // Has Auth Filter
    });

    Route::get('user/profile', function()
    {
        // Has Auth Filter
    });
});
```

That way, the middleware is used only for some routes. Any thoughts?

2) Same here, I want global **orders** subscription only for admin pages. I can specify in every route this subscription, but for a group it would be much better. Any ideas?

3) Okay, would use a new layout. +

4) Okay, would insert the meteor way. +

5, 6, the bonus one) Okay, I will try to create a repository with this small example till weekend. + -

second bonus question) What is the supposed way of storing routes? Now, I have directories in client for components (orders e.g.), there I store router file (`/client/views/orders/lib/router.js`). But the docs say, put in the lib dir. What is the correct way?

**Comment by arunoda** [comment] 2015-03-18 00:51
1) Router.group is really good syntax. I think we could have it.
You can also have a admin route like this:

/admin/:category
/admin/:category/:id
/admin/:category/:id/:slug

2) I think Router.group will solve that.

3) You can put it anywhere in the client. But I prefer having it inside the
/lib directory. With that, we can have fast-render support. But that's not
a rule.

**Comment by VladShcherbin** [comment] 2015-03-18 12:31
@arunoda thank you, the route groups would be awesome!

You can check the [http://laravel.com/docs/5.0/routing#route-groups](laravel router docs), just watch the examples, they are straightforward, maybe we take smth from there (prefix, naming routes). Lots of people love laravel for how it is done and the router there is awesome and intuitive.

It would be very cool, if this package would provide similar functionality. Flow architecture is a nice alternative to a confusing IR.

**Comment by arunoda** [comment] 2015-03-18 12:37
I've the API in mind. I fill do it in few days.

**Comment by VladShcherbin** [comment] 2015-03-18 12:39
@arunoda thank you. you do a great job. keep going!

**Comment by delgermurun** [comment] 2015-03-19 01:40
Looking forward grouping :+1:

**Comment by arunoda** [comment] 2015-03-28 12:08
Hope we can close this.
Route grouping is moved to #46

**Closed by arunoda** 2015-03-28 12:08 UTC

**Comment by yuomtheara** [comment] 2015-03-29 07:16
Look great for router group and middleware style.
I used to `Laravel`, it is good for router.
