### ISSUE TITLE
route not changed with FlowRouter.go()

### ISSUE THREAD

**Issue by KristerV** [meteorhacks/flow-router#202] opened 2015-07-11 08:11 UTC
Perhaps this is by design, but frustrated me just now (first time using FR).

		FlowRouter.route('/', {
			action: function(params) {
				FlowLayout.render('landing')
			}
		});
		FlowRouter.route('/neworder/', {
			action: function(params) {
				FlowLayout.render('neworder') // line 8
			}
		});

If line 8 is missing, then calling `FlowRouter.go('/neworder')` from route `/` runs the new routes action, but the old `FlowLayout.render('landing')` stays in the view with no errors or anything. Being accustumed ti iron:router I naturally would expect an error and so I spent a good hour looking for the issue elsewhere. Very annoying.

**Comment by arunoda** [comment] 2015-07-11 09:04
Yes it is by design. Router know nothing about the views.
However you can catch not found routes.

**Comment by KristerV** [comment] 2015-07-11 16:57
Oh, so because there is no new view to render the old one stays in place and thus it's the Layout manager problem? Or rather it seems it's the problem with the two not working together. How can I catch an empty route?

**Comment by arunoda** [comment] 2015-07-11 22:18
It's not a problem. It's how it's being built.
Try not to write empty routes. If there is no matching route, we'll call the notFound route.
But, we can't do anything if it's not defined in the action.

**Comment by arunoda** [comment] 2015-07-15 04:31
I think I'm going to close this now.

**Closed by arunoda** 2015-07-15 04:31 UTC

**Comment by KristerV** [comment] 2015-07-15 11:09
yep, safe to be closed. Especially since this is now googleable.
